import pandas as spd
import matplotlib.pyplot as plt
df = spd.read_csv("stars_with_gravity.csv")
m = df["Mass"].to_list()
r = df["Radius"].to_list()
d = df["Distance"].to_list()
g = df["gravity"].to_list()
m.sort()
r.sort()
d.sort()
g.sort()
plt.plot(r,m)
plt.title("mass vs gravity")
plt.xlabel("Mass")
plt.ylabel("gravity")
plt.show()
plt.scatter(r,m)
plt.xlabel("Radius")
plt.ylabel("Mass")
plt.show()
plt.scatter(r,g)
plt.xlabel("Radius")
plt.ylabel("gravity")
plt.show()